### ISSUE TITLE
Is it possible to disable the filter dialog?

### ISSUE THREAD

**Issue by OfficiallyMellow** [groggyegg/plugin.video.dramacool#18]
I am not sure, if this was caused by an addon update or switching to Matrix.
In the past, when I, for example, navigated to Drama List/Thailand Drama, I got a "list view" of the filters, but now they show up as a dialog.
Unfortunately, because of that, I can not add any content of this addon as "homescreen widgets" anymore (using Arctic Horizon skin), because whenever a widget refreshes, the filter dialog pops up again, which is pretty annoying.
Is there any way to make it work the "old way"?

Anyways, keep up the great work on this addon!

Sorry for my english and thanks in advance!
Any help is appreciated.

**Comment by groggyegg** [comment]
Unfortunately this was changed in Kodi 19. The reason was to make it more easier to search for specific dramas/movies. There's currently no plan to add support for the old way. The only change I could think of is to add a search history list which should solve the problem you have. But that would be for later when I have time.

**Comment by OfficiallyMellow** [comment]
Awesome, thanks for your response. I'll be patiently looking forward to this change.

Kind Regards.

**Comment by groggyegg** [comment]
Fixed with commit c37119dfcac6120aafcf5cb4c6bab07dbc0ddff8.
