### ISSUE TITLE
Dramacool not loading videos

### ISSUE THREAD

**Issue by BedrosBoost** [groggyegg/plugin.video.dramacool#37]
I'm unable to play videos for the series Again My Life. Updated to the latest version and tried all the links. This is the debug file
http://paste.kodi.tv/jacobipiva

**Comment by groggyegg** [comment]
In the debug file it mentions
`script.module.resolveurl v5.1.67 installed`

Latest version is v5.1.70, could you try update resolveurl and report back.

**Comment by groggyegg** [comment]
Also, I have just checked the link in browser. It seems that the link has been taken down. Does other video works? If yes, then there's nothing more we can do about it.

**Comment by BedrosBoost** [comment]
Alright, I've updated it to v5.1.70 but it's still the same. I tried all the different mirrors for two different episodes and none of them work for some reason. http://paste.kodi.tv/kusovugiqu

**Comment by stvg88** [comment]
@BedrosBoost the video itself has been taken down (probably DMCA'ed) on dramacool site. Seems like only streamsb is still working now, but you need ResolveURL dev to push the fix for it to his kodi repo.
If you can't wait and you have some basic coding knowledge, you can manually update resolver code for streamsb based on [this commit](https://github.com/Gujal00/ResolveURL/commit/5a26f2ff4eaee10b9583fbfdcfc18dda9ec42137), otherwise just wait for ResolveURL to be updated.

**Comment by BedrosBoost** [comment]
@stvg88 Ah alright thanks. Guess they took down the videos for all the episodes then, which I didn't expect. I later went to test out videos for other series and they worked fine, so you're probably right.
