### ISSUE TITLE
Show native language titles as well?

### ISSUE THREAD

**Issue by badbob001** [groggyegg/plugin.video.dramacool#4]
Currently only the english titles are show. Can the native language titles (eg: chinese) be shown next to the english titles? Or have an option to toggle this (english/native/both)?

**Comment by groggyegg** [comment]
I will think about it. The issue is that:
1. Not every drama has a native title on dramacool website
2. The title does not conform to a specific structure, the title can sometimes contain only chinese or a combination of chinese and english, which makes it a bit of a pain to work with.
3. There is no way to identify if the title is in chinese, japanese, english etc. on their website.

**Comment by badbob001** [comment]
I checked out the site and there is actually very little native language titles there. Oh well.
