### ISSUE TITLE
Time stamps/resume position aren't working on kodi 20

### ISSUE THREAD

**Issue by cbizzle14** [groggyegg/plugin.video.dramacool#44]
I'm going to assume this is an issue with kodi 20? Xbox just updated from 19.4 and now resume position aren't working. This includes marking an episode as watched. It'll go through and look like it's working but once you exit kodi and come back it's like you never watched the episode before

**Comment by cbizzle14** [comment]
Also what's up with all the posters being the same white background with two characters on it, one up and one bottom with the text going across the middle? Accessing the website the show posters are completely different and detailed

**Comment by groggyegg** [comment]
> I'm going to assume this is an issue with kodi 20? Xbox just updated from 19.4 and now resume position aren't working. This includes marking an episode as watched. It'll go through and look like it's working but once you exit kodi and come back it's like you never watched the episode before

I haven't used it for a while so I'm not sure if anything has changed. But last time I checked, it worked with Kodi 20. I will have to test the addon again. Do you have any logs that you could upload?

> Also what's up with all the posters being the same white background with two characters on it, one up and one bottom with the text going across the middle? Accessing the website the show posters are completely different and detailed

Need an image to know what you are talking about. But will look into it when I have time.

**Comment by groggyegg** [comment]
This is an expected behaviour. The addon keeps an internal database that contains information from dramacool at a certain time which is used when showing dramas. This is to improve the performance otherwise the loading might take a few minutes. The data will not get updated when change happens on the website. Instead, this needs to be done manually which I haven't done for the past few months. But I will update the db at the end of this month or beginning of next month.

**Comment by cbizzle14** [comment]
Thanks for the explanation. Hadn't seen it before so was curious. Happy holidays
