### ISSUE TITLE
Dependency issues on install on Matrix 

### ISSUE THREAD

**Issue by PtahX** [groggyegg/plugin.video.dramacool#5]
I'm just playing around with this for the wife on the Kodi Matrix Build, https://groggyegg.github.io/ install is giving failed dependancies on:

script.module.lxml  (I haven't been able to locate a matrix version yet) 
script.module.cryptopy (I haven't been able to locate a matrix version yet) 
youtube (about to look for it)
plugin.googledrive (about to look for it) 

but the repo shows up with the option to install on the current build - appreciate your time on this :)

**Comment by fredrik-sy** [comment]
The lime repository contains the old version and does not have support for Kodi 19. While the code in addon has support for Kodi 19, the changes won't be sent to lime repository yet since Kodi 19 is still in the beta. If you want to try it on Kodi 19, you have to manually download the zip file and install it. I might add it to https://groggyegg.github.io/ if people don't have the option to install it from the zip file.

Regarding the dependency, script.module.lxml should be optional and shouldn't be required when installing the addon. This addon only requires script.module.resolveurl and script.module.requests. So the script.module.cryptopy, youtube and plugin.googledrive might be related to those modules.

**Comment by groggyegg** [comment]
The lime repository contains the old version and does not have support for Kodi 19. While the code in addon has support for Kodi 19, the changes won't be sent to lime repository yet since Kodi 19 is still in the beta. If you want to try it on Kodi 19, you have to manually download the zip file and install it. I might add it to https://groggyegg.github.io/ if people don't have the option to install it from the zip file.

Regarding the dependency, script.module.lxml should be optional and shouldn't be required when installing the addon. This addon only requires script.module.resolveurl and script.module.requests. So the script.module.cryptopy, youtube and plugin.googledrive might be related to those modules.

Make sure that you install the resolveurl and a zip file of the changes made to this addon, because that's the only thing needed when running this addon.

**Comment by groggyegg** [comment]
A quick update, there seems to be some issue where ResolveURL can't be installed/pulled from the repo when installing the dramacool addon in Kodi 19 Matrix. This does not seem to happen in Kodi 18 Leia. Installing separately seems to work. I'll wait with debugging the issue and see if the issue still persist once the Matrix has been officially released.

**Comment by PtahX** [comment]
> A quick update, there seems to be some issue where ResolveURL can't be installed/pulled from the repo when installing the dramacool addon in Kodi 19 Matrix. This does not seem to happen in Kodi 18 Leia. Installing separately seems to work. I'll wait with debugging the issue and see if the issue still persist once the Matrix has been officially released.

I had the same issue when I was testing it out in 19 as well, I haven't had time to work with it but it's on the to do list. Than you for the update:)

**Comment by du2uxh** [comment]
I am trying to install Dramacool in Kodi 18.6 Leia and followed the instruction on how to install it.  Unfortunately the script.module.resolveurl says not available.  Is there any update on how to get Dramacool running in Kodi?

**Comment by groggyegg** [comment]
I have updated the lime repository to include resolveurl. The issue mentioned before does not occur when installing from a clean Kodi (Matrix). Need someone who can confirm it before I close this issue.

@du2uxh Try the instructions again https://github.com/groggyegg/groggyegg.github.io Make sure that you don't have any leftover from old dramacool addon that could conflict with this addon.

**Comment by du2uxh** [comment]
Happy New Year and thank you for your email.  It worked.

Again, thanks for your help.

du2uxh
